# Site Settings
title:               Karan Agarwal
tagline:
description:
baseurl:
url:                "http://blog.karanagarwal.me"
github:
  url:               "http://blog.karanagarwal.me"
author:
  name:              "Karan Agarwal"
  email:             "karanagarwal1702@gmail.com"
  twitter:           "karanagarwal17"
  github:            "karanagarwal17"
  facebook:          "karanagarwal17"
  linkedin:          "karanagarwal17"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           pretty
gems:                [jekyll-paginate]

exclude: ["README.md","CNAME",".gitignore","LICENSE"]
